sudo: required
language: node_js
node_js:
  - "6"

install:
    - cd server
    - npm install
    - npm install istanbul
    - cd ../client
    - npm install

script:
    - npm test
    - cd ../server
    - node ./bin/www &
    - npm test

before_install:
    - openssl aes-256-cbc -K $encrypted_b0a09f49a4ef_key -iv $encrypted_b0a09f49a4ef_iv
      -in ./server/secrets.tar.enc -out ./server/secrets.tar -d
    - tar xvf ./server/secrets.tar -C ./server/

after_script:
  - NODE_ENV=test istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec 
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - rm -rf ./coverage


#    - openssl aes-256-cbc -K $encrypted_b0a09f49a4ef_key -iv $encrypted_b0a09f49a4ef_iv
#      -in ./server/auth.js.enc -out ./server/config/auth.js -d
#    - openssl aes-256-cbc -K $encrypted_b0a09f49a4ef_key -iv $encrypted_b0a09f49a4ef_iv
#      -in ./server/twillio-keys.js.enc -out ./server/config/twillio-keys.js -d
