sudo: required
language: node_js
node_js:
  - "6"

install:
    - cd server
    - npm install
    - cd ../client
    - npm install

script:
    - npm test
    - cd ../server
    - node ./bin/www &
    -
    - npm test

before_install:
    - mkdir server/config
    - openssl aes-256-cbc -K $encrypted_b0a09f49a4ef_key -iv $encrypted_b0a09f49a4ef_iv
      -in ./server/auth.js.enc -out ./server/config/auth.js -d